### ISSUE TITLE
Execution of JApiCmp failed: Optional.get() with 0.7.1 and 0.7.2

### ISSUE THREAD

**Issue by ccz99** [siom79/japicmp#130]
I hit the below exception with 0.7.1 and 0.7.2. But there is no issue with 0.7.0. So a regression should be introduced here.

Execution of JApiCmp failed: Optional.get() cannot be called on an absent value
java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
        at com.google.common.base.Absent.get(Absent.java:47)
        at japicmp.model.JApiException.isCheckedException(JApiException.java:25)
        at japicmp.model.JApiException.<init>(JApiException.java:18)
        at japicmp.model.JApiBehavior.computeExceptionChanges(JApiBehavior.java:66)
        at japicmp.model.JApiBehavior.<init>(JApiBehavior.java:53)
        at japicmp.model.JApiMethod.<init>(JApiMethod.java:17)
        at japicmp.model.JApiClass.sortMethodsIntoLists(JApiClass.java:329)
        at japicmp.model.JApiClass.computeMethodChanges(JApiClass.java:304)
        at japicmp.model.JApiClass.<init>(JApiClass.java:51)
        at japicmp.cmp.ClassesComparator.sortIntoLists(ClassesComparator.java:50)
        at japicmp.cmp.ClassesComparator.compare(ClassesComparator.java:30)
        at japicmp.cmp.JarArchiveComparator.compareClassLists(JarArchiveComparator.java:183)
        at japicmp.cmp.JarArchiveComparator.createAndCompareClassLists(JarArchiveComparator.java:161)
        at japicmp.cmp.JarArchiveComparator.compare(JarArchiveComparator.java:72)
        at japicmp.cli.JApiCli$Compare.run(JApiCli.java:74)
        at japicmp.JApiCmp.main(JApiCmp.java:16)

**Comment by siom79** [comment]
Since 0.7.1 exceptions are loaded from the classpath. If this fails, you currently see the above error message. Improved this on the `develop` branch.
