### ISSUE TITLE
NullPointerException when no parameter section provided in configuration

### ISSUE THREAD

**Issue by chonton** [siom79/japicmp#134]
If configuration does not have parameter section, the following NullPointerException occurs.
```
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.github.siom79.japicmp:japicmp-maven-plugin:0.8.0:cmp failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.NullPointerException
        at japicmp.maven.JApiCmpMojo.filterModule(JApiCmpMojo.java:178)
        at japicmp.maven.JApiCmpMojo.executeWithParameters(JApiCmpMojo.java:108)
        at japicmp.maven.JApiCmpMojo.execute(JApiCmpMojo.java:100)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more

```

**Comment by siom79** [comment]
Will be released with 0.8.1. Thanks for reporting.
