### ISSUE TITLE
Missing javax/xml/bind/JAXBException when executing on JDK 9

### ISSUE THREAD

**Issue by io7m** [siom79/japicmp#177]
Hello.

I'm in the process of moving my projects to Java 9. I'm seeing errors like the following when executing `japicmp`:

```
[ERROR] Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.10.0:cmp (default) on project com.io7m.jnull.checkstyle: Execution default of goal com.github.siom79.japicmp:japicmp-maven-plugin:0.10.0:cmp failed: A required class was missing while executing com.github.siom79.japicmp:japicmp-maven-plugin:0.10.0:cmp: javax/xml/bind/JAXBException
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.siom79.japicmp:japicmp-maven-plugin:0.10.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/someone/.m2/repository/com/github/siom79/japicmp/japicmp-maven-plugin/0.10.0/japicmp-maven-plugin-0.10.0.jar
[ERROR] urls[1] = file:/home/someone/.m2/repository/org/apache/maven/maven-aether-provider/3.0.3/maven-aether-provider-3.0.3.jar
[ERROR] urls[2] = file:/home/someone/.m2/repository/org/sonatype/aether/aether-util/1.11/aether-util-1.11.jar
[ERROR] urls[3] = file:/home/someone/.m2/repository/org/sonatype/sisu/sisu-inject-bean/2.1.1/sisu-inject-bean-2.1.1.jar
[ERROR] urls[4] = file:/home/someone/.m2/repository/org/sonatype/sisu/sisu-guice/2.9.4/sisu-guice-2.9.4-no_aop.jar
[ERROR] urls[5] = file:/home/someone/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[6] = file:/home/someone/.m2/repository/org/codehaus/plexus/plexus-utils/2.0.6/plexus-utils-2.0.6.jar
[ERROR] urls[7] = file:/home/someone/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[8] = file:/home/someone/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[9] = file:/home/someone/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[10] = file:/home/someone/.m2/repository/com/github/siom79/japicmp/japicmp/0.10.0/japicmp-0.10.0.jar
[ERROR] urls[11] = file:/home/someone/.m2/repository/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar
[ERROR] urls[12] = file:/home/someone/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
[ERROR] urls[13] = file:/home/someone/.m2/repository/io/airlift/airline/0.7/airline-0.7.jar
[ERROR] urls[14] = file:/home/someone/.m2/repository/com/google/code/findbugs/annotations/2.0.3/annotations-2.0.3.jar
[ERROR] urls[15] = file:/home/someone/.m2/repository/org/apache/maven/reporting/maven-reporting-impl/2.3/maven-reporting-impl-2.3.jar
[ERROR] urls[16] = file:/home/someone/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[17] = file:/home/someone/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[18] = file:/home/someone/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.6/maven-shared-utils-0.6.jar
[ERROR] urls[19] = file:/home/someone/.m2/repository/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
[ERROR] urls[20] = file:/home/someone/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.2/doxia-sink-api-1.2.jar
[ERROR] urls[21] = file:/home/someone/.m2/repository/org/apache/maven/doxia/doxia-core/1.2/doxia-core-1.2.jar
[ERROR] urls[22] = file:/home/someone/.m2/repository/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
[ERROR] urls[23] = file:/home/someone/.m2/repository/org/apache/httpcomponents/httpclient/4.0.2/httpclient-4.0.2.jar
[ERROR] urls[24] = file:/home/someone/.m2/repository/org/apache/httpcomponents/httpcore/4.0.1/httpcore-4.0.1.jar
[ERROR] urls[25] = file:/home/someone/.m2/repository/commons-codec/commons-codec/1.3/commons-codec-1.3.jar
[ERROR] urls[26] = file:/home/someone/.m2/repository/org/apache/maven/doxia/doxia-site-renderer/1.2/doxia-site-renderer-1.2.jar
[ERROR] urls[27] = file:/home/someone/.m2/repository/org/apache/maven/doxia/doxia-decoration-model/1.2/doxia-decoration-model-1.2.jar
[ERROR] urls[28] = file:/home/someone/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.2/doxia-module-xhtml-1.2.jar
[ERROR] urls[29] = file:/home/someone/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.2/doxia-module-fml-1.2.jar
[ERROR] urls[30] = file:/home/someone/.m2/repository/org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n-1.0-beta-7.jar
[ERROR] urls[31] = file:/home/someone/.m2/repository/org/codehaus/plexus/plexus-velocity/1.1.7/plexus-velocity-1.1.7.jar
[ERROR] urls[32] = file:/home/someone/.m2/repository/org/apache/velocity/velocity/1.5/velocity-1.5.jar
[ERROR] urls[33] = file:/home/someone/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar
[ERROR] urls[34] = file:/home/someone/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar
[ERROR] urls[35] = file:/home/someone/.m2/repository/commons-validator/commons-validator/1.3.1/commons-validator-1.3.1.jar
[ERROR] urls[36] = file:/home/someone/.m2/repository/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar
[ERROR] urls[37] = file:/home/someone/.m2/repository/commons-digester/commons-digester/1.6/commons-digester-1.6.jar
[ERROR] urls[38] = file:/home/someone/.m2/repository/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.jar
[ERROR] urls[39] = file:/home/someone/.m2/repository/commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.jar
[ERROR] urls[40] = file:/home/someone/.m2/repository/org/apache/maven/reporting/maven-reporting-api/2.2.1/maven-reporting-api-2.2.1.jar
[ERROR] urls[41] = file:/home/someone/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.jar
[ERROR] urls[42] = file:/home/someone/.m2/repository/org/codehaus/groovy/groovy-jsr223/2.4.6/groovy-jsr223-2.4.6.jar
[ERROR] urls[43] = file:/home/someone/.m2/repository/org/codehaus/groovy/groovy/2.4.6/groovy-2.4.6.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>com.io7m.jnull:com.io7m.jnull:2.0.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : javax.xml.bind.JAXBException
```

Is this a known issue?

**Comment by siom79** [comment]
Hello,

japicmp does currently not support Java 9 as there is still no official
release of javassist with Java 9 support. Anyhow, with Java 9 the java.xml
package is no longer part of the base module. You have to add it as
required module.

Best Regards
Martin

**Comment by io7m** [comment]
OK, thanks. I'll keep an eye out for updates to Javassist.

**Comment by io7m** [comment]
It looks like they have a 9-compatible general availability release now:

https://github.com/jboss-javassist/javassist/releases/tag/rel_3_22_0_ga

**Comment by io7m** [comment]
Heh, sorry, I just spotted your latest commit! You're ahead of me. 👍

**Comment by io7m** [comment]
FYI, I've tested the latest commit and it works well; it fixes the exception in this bug. I'll close this ticket.

**Comment by robinst** [comment]
Is this fixed in a release yet? I'm having the same problem with version 0.11.0.

**Comment by siom79** [comment]
For Java 9 you must add the java.xml.bind module via MAVEN_OPTS as described in the README.MD. Unfortunately there is currently no other way to fix this internally.

**Comment by reckart** [comment]
Actually, it seems this can be fixed without resorting to setting MAVEN_OPTS. The following worked ok for me:

```
          <plugin>              
            <groupId>com.github.siom79.japicmp</groupId>
            <artifactId>japicmp-maven-plugin</artifactId>
            <version>0.11.1</version>
            <configuration>
              ...
            </configuration>
            ...
            <dependencies>
              <dependency>
                <groupId>javax.xml.bind</groupId>
                <artifactId>jaxb-api</artifactId>
                <version>2.3.0</version>
              </dependency>
              <dependency>
                <groupId>com.sun.xml.bind</groupId>
                <artifactId>jaxb-core</artifactId>
                <version>2.3.0</version>
              </dependency>
              <dependency>
                <groupId>com.sun.xml.bind</groupId>
                <artifactId>jaxb-impl</artifactId>
                <version>2.3.0</version>
              </dependency>
              <dependency>
                <groupId>javax.activation</groupId>
                <artifactId>javax.activation-api</artifactId>
                <version>1.2.0</version>
              </dependency>
            </dependencies>
          </plugin>
```

Cf. https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j/43574427

**Comment by twogee** [comment]
Does that work with Java 7 and 8?

**Comment by io7m** [comment]
FYI: JDK 11 actually removes the `java.xml.bind` and `java.xml.ws.annotation` modules entirely.

**Comment by twogee** [comment]
I'm afraid the solution might be a multi release jar.

**Comment by hkalina** [comment]
@twogee the added <dependencies> builds OK on Oracle JDK 8 and IBM JDK 8 too.

**Comment by sabitashrestha** [comment]
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at org.jboss.logging.Logger.getMessageLogger(Logger.java:2248)
        at org.jboss.logging.Logger.getMessageLogger(Logger.java:2214)
        at org.hibernate.validator.internal.util.logging.LoggerFactory.make(LoggerFactory.java:29)
        at org.hibernate.validator.internal.util.Version.<clinit>(Version.java:27)
        at org.hibernate.validator.internal.engine.ConfigurationImpl.<clinit>(ConfigurationImpl.java:65)
        at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:41)
        at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:276)
        at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:110)
        at io.dropwizard.setup.Bootstrap.<init>(Bootstrap.java:62)
        at io.dropwizard.Application.run(Application.java:67)
        at com.trivago.case_study_ps.CaseStudyPSApplication.main(CaseStudyPSApplication.java:20)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)

I am having this issue while executing the jar files :(

**Comment by siom79** [comment]
@sabitashrestha Which version of japicmp do you use? For older versions you may have to set `--add-modules java.xml.bind` (for more details see [here](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j/47842891). Since 0.13.0 you shouldn't need this anymore.

**Comment by twogee** [comment]
please see #183, current dependencies are too old; according to [release notes](https://javaee.github.io/jaxb-v2/doc/user-guide/release-documentation.html#a-2-3-0) JAXB 2.3.0 is the first release that supports Java 9.
