### ISSUE TITLE
Could not load 'SuperclassNotExisting': SuperclassNotExisting.How to set classpath

### ISSUE THREAD

**Issue by yuanxiaomama** [siom79/japicmp#245]
`options = Options.newDefault();
        options.setIgnoreMissingClasses(false);
        options.setAccessModifier(AccessModifier.PRIVATE);
        options.setOldArchives(oldArchiveList);
        options.setNewArchives(newArchiveList);
        options.setOldClassPath(oldClassPath);
        options.setNewClassPath(newClassPath);`

in project, there is no error message, but there is error in command 

E: Could not load 'Class not found: org.springframework.beans.factory.FactoryBean': org.springframework.beans.factory.FactoryBean. Please make sure that all libraries have been added to the classpath (OLD CLASSPATH=:core-2.8.0.jar: / NEW CLASSPATH=:core-2.8.1.jar:) or try the option '--ignore-missing-classes'.

**Comment by yuanxiaomama** [comment]
`JarArchiveComparatorOptions comparatorOptions = JarArchiveComparatorOptions.of(options);
        JarArchiveComparator jarArchiveComparator = new JarArchiveComparator(comparatorOptions);

        jApiClasses = jarArchiveComparator.compare(oldArchive, newArchive);
        try {
            generateHtmlOutputOnlyModifications();
        } catch (IOException e) {
            e.printStackTrace();
        }`

japicmp.exception.JApiCmpException: Could not load 'SuperclassNotExisting': SuperclassNotExisting. Please make sure that all libraries have been added to the classpath (CLASSPATH=) or try the option '--ignore-missing-classes'.
	at japicmp.exception.JApiCmpException.forClassLoading(JApiCmpException.java:50) ~[japicmp-0.14.1.jar:?]
	at japicmp.model.JApiClass.getSuperclass(JApiClass.java:269) ~[japicmp-0.14.1.jar:?]
	at japicmp.model.JApiClass.extractSuperclass(JApiClass.java:227) ~[japicmp-0.14.1.jar

Is the usage wrong?
