### ISSUE TITLE
ArtifactNotFoundException when comparison list is build from maven project

### ISSUE THREAD

**Issue by siom79** [siom79/japicmp#278]
```
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.github.siom79.japicmp:japicmp::0.15.0 in central (https://repo.maven.apache.org/maven2)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:365)
```

**Comment by siom79** [comment]
Fixed: 0.15.1
