### ISSUE TITLE
Removed class prevents analysis

### ISSUE THREAD

**Issue by bondolo** [siom79/japicmp#79]
After some heavy refactoring japicmp can no longer generate diffs. The problem is a class that was removed. Previously this class had been the superclass of a class which still exists.

Adding an &lt;excludes>&lt;exclude>com.example.package.SomeClass&lt;/exclude>&lt;excludes> does not help.

    Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.github.siom79.japicmp:japicmp-maven-plugin:0.6.0:cmp failed: com.example.package.SomeClass
            at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
            at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
            ... 20 more
    Caused by: japicmp.exception.JApiCmpException: com.example.package.SomeClass
            at japicmp.model.JApiClass.getSuperclass(JApiClass.java:227)
            at japicmp.model.JApiClass.extractSuperclass(JApiClass.java:186)
            at japicmp.model.JApiClass.<init>(JApiClass.java:50)
            at japicmp.cmp.ClassesComparator.sortIntoLists(ClassesComparator.java:50)
            at japicmp.cmp.ClassesComparator.compare(ClassesComparator.java:30)
            at japicmp.cmp.JarArchiveComparator.compareClassLists(JarArchiveComparator.java:170)
            at japicmp.cmp.JarArchiveComparator.createAndCompareClassLists(JarArchiveComparator.java:149)
            at japicmp.cmp.JarArchiveComparator.compare(JarArchiveComparator.java:62)
            at japicmp.maven.JApiCmpMojo.compareArchives(JApiCmpMojo.java:303)
            at japicmp.maven.JApiCmpMojo.executeWithParameters(JApiCmpMojo.java:101)
            at japicmp.maven.JApiCmpMojo.execute(JApiCmpMojo.java:75)
            at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
            ... 21 more
    Caused by: javassist.NotFoundException: com.example.package.SomeClass
            at javassist.ClassPool.get(ClassPool.java:452)
            at javassist.CtClassType.getSuperclass(CtClassType.java:725)
            at japicmp.model.JApiClass.getSuperclass(JApiClass.java:221)
            ... 32 more

**Comment by siom79** [comment]
Is the missing class still available on the classpath? If not, you can try the option ignoreMissingClasses.

**Comment by bondolo** [comment]
Adding ignoreMissingClasses option did allow japicmp to complete. The class reported missing is still available in the old version though it is absent in the new version. Using ignoreMissingClasses doesn't feel correct for this situation.

**Comment by siom79** [comment]
The test module `japicmp-test-v1` contains the class `japicmp.test.Removed`, which is removed in version 2 of this module. Running the following command on the current `develop` branch outputs the class as removed:
```
java -cp japicmp/target/japicmp-0.6.1-SNAPSHOT-jar-with-dependencies.jar:/home/mmois/.m2/repository/org/apache/commons/commons-math3/3.4/commons-math3-3.4.jar japicmp.JApiCmp -o japicmp-testbase/japicmp-test-v1/target/japicmp-test-v1-0.6.1-SNAPSHOT.jar -n japicmp-testbase/japicmp-test-v2/target/japicmp-test-v2-0.6.1-SNAPSHOT.jar | grep "REMOVED CLASS"
---! REMOVED CLASS: PUBLIC(-) japicmp.test.jpa.RemovedEntity  (not serializable)
---! REMOVED CLASS: PUBLIC(-) japicmp.test.Removed  (not serializable)
---! REMOVED CLASS: PUBLIC(-) STATIC(-) japicmp.test.serialversion.CompatibleChanges$ClassRemoved  (class removed)
---! REMOVED CLASS: PUBLIC(-) japicmp.test.serialversion.SerializableClassRemoved  (class removed)
---! REMOVED CLASS: PUBLIC(-) STATIC(-) japicmp.test.Superclasses$RemovedWithSuperclass  (not serializable)
---! REMOVED CLASS: PUBLIC(-) japicmp.test.TypedField  (not serializable)
```

**Comment by bondolo** [comment]
OK, I will try to make a replication example.

**Comment by siom79** [comment]
@bondolo Did you find some time to create an example?

**Comment by bondolo** [comment]
Not yet, sorry.
